### ISSUE TITLE
Missing reference on README

### ISSUE THREAD

**Issue by aerdem4** [ing-bank/popmon#12]
It would be nice to give reference to people who have worked on it, considering that you have committed the whole project using your accounts. I see that some significant portion of this project is written by me and I believe some other ex-colleagues contributed as well.

**Comment by tomcis** [comment]
Indeed, it would be great to find a nice way to refer to everyone who has contributed to this project. We do not claim sole ownership of the code whatsoever - that's why we have explicitly mentioned authors as the whole team: ING Wholesale Banking Advanced Analytics. Since the code was migrated from the company's internal GitLab repository, all git history had to be cleaned (and consequently someone, who, in this case, appeared to be me, had to initialize the first commit with all the code here on GitHub). We are open to any suggestions from your side on what would be the best way to give a shoutout to all the people who have contributed in any way!

**Comment by aerdem4** [comment]
The code is owned by ING. There is no objection to that. But author/contributor and owner are different terms. A list of past contributors on README can be an easy solution. If the project is going to be maintained over Github, you won't need to update this list every time because Github will keep track of contributors.
